export enum HttpStatus {

    /* Information */
    Continue = 100,
    Switching_Protocols = 101,
    Processing = 102,

    /* Success */
    OK = 200,
    Created = 201,
    Accepted = 202,
    Non_Authoritative_Information = 203,
    No_Content = 204,
    Reset_Content = 205,
    Partial_Content = 206,
    Multi_Status = 207,
    Content_Different = 210,
    IM_Used = 226,

    /* Redirection */
    Multiple_Choices = 300,
    Moved_Permanently = 301,
    Moved_Temporarily = 302,
    See_Other = 303,
    Not_Modified = 304,
    Use_Proxy = 305,
    Temporarily_Redirect = 307,
    Permanently_Redirect = 308,
    Too_Many_Redirects = 310,

    /* Client Error */
    Bad_Request = 400,
    Unauthorized = 401,
    Payment_Required = 402,
    Forbidden = 403,
    Not_Found = 404,
    Method_Not_Allowed = 405,
    Not_Acceptable = 406,
    Proxy_Authentification_Required = 407,
    Request_Timeout = 408,
    Conflict = 409,
    Gone = 410,
    Length_Required = 411,
    Precondition_Failed = 412,
    Request_Entity_Too_Large = 413,
    Request_URI_Too_Long = 414,
    Unsupported_Media_Type = 415,
    Request_Range_Unsatisfiable = 416,
    Expectation_Failed = 417,
    Im_a_Teapot = 418,
    Bad_Mapping = 421,
    Unprocessable_entity = 422,
    Locked = 423,
    Method_Failure = 424,
    Unordered_Collection = 425,
    Upgrade_Required = 426,
    Precondition_Required = 428,
    Too_Many_Requests = 429,
    Request_Header_Fields_Too_Large = 431,
    Unrecoverable_Error = 456,

    /* Server Error */
    Internal_Server_Error = 500,
    Not_Implemented = 501,
    Bad_Gateway = 502,
    Service_Unavailable = 503,
    Gateway_Timeout = 504,
    HTTP_Version_Not_Supported = 505,
    Variant_Also_Negotiated = 506,
    Insufficient_Storage = 507,
    Loop_Detected = 508,
    Bandwidth_Limit_Exceeded = 509,
    Not_Extended = 510,
    Network_Authentification_Required = 511
}
